export const previewTrace = {
  language: "tr",
  question: "Entropi neden hep artar?",
  title: "Entropi neden hep artar?",
  answer: [
    {
      id: "answer-1",
      text: "Entropi, kapalı bir sistemde kendiliğinden gerçekleşen süreçlerin yönünü belirleyen bir ölçüdür. Sistemler, mikroskobik olasılıkların çoğuna karşılık gelen hâllerine doğru eğilir. Bu yüzden izole bir sistemde entropi ya artar ya da sabit kalır; azalması ancak dışarıdan düzenli enerji girdisiyle mümkündür.",
    },
    {
      id: "answer-2",
      text: "Rudolf Clausius, 19. yüzyılda ısının işe dönüşebilmesinin sınırlarını araştırırken entropi kavramını formülleştirdi. Isının kendiliğinden sıcak olandan soğuk olana geçmesiyle entropi artışı arasındaki bağlantı, doğal süreçlerin neden belirli bir yönde ilerlediğini açıklayan ortak bir dil sağladı.",
    },
    {
      id: "answer-3",
      text: "Ludwig Boltzmann daha sonra bu fikri mikroskobik durumların olasılığıyla ilişkilendirdi. Bir sistemi oluşturan parçacıklar için düzensiz görünen durumların sayısı çok daha fazladır; sistemin bu durumlara yönelmesi bu nedenle son derece olasıdır.",
    },
    {
      id: "answer-4",
      text: "Bu düşünce tek bir anda ortaya çıkmadı. Carnot’nun ısı makineleri üzerine sorduğu sorular, Clausius’un kavramsal dili, Boltzmann’ın istatistiksel yaklaşımı ve adı kayda geçmeyen mühendislerin uygulamaları birbirine eklenerek bugünkü açıklamayı oluşturdu.",
    },
  ],
  traceStatus: "available",
  traceReason: "Kavram, birbirine eklenen bilimsel ve mühendislik katkılarıyla oluştu.",
  acknowledgement: "Bu yanıt, birbirine eklenen insan emeğine dayanıyor.",
  contributors: [
    {
      id: "carnot",
      name: "Sadi Carnot",
      entityType: "person",
      role: "başlangıç sorusu",
      summary: "Isı makinelerinin verim sınırını araştırarak ikinci yasanın kurulacağı soruyu görünür hale getirdi.",
      story: "Carnot, buhar makinelerinin ne kadar verimli olabileceğini anlamaya çalışırken ısının hareketi ile iş üretimi arasındaki temel sınırı tarif etti. Çalışması entropi terimini kullanmıyordu; fakat sonraki araştırmacıların üzerine kuracağı problemi berraklaştırdı.",
      relationshipToPrevious: "Akışın başlangıcındaki mühendislik sorusu",
      paragraphIds: ["answer-4"],
      sourceIds: ["source-1"],
    },
    {
      id: "clausius",
      name: "Rudolf Clausius",
      entityType: "person",
      role: "kavramsal dil",
      summary: "Entropiyi tanımlayıp ikinci yasayı doğal süreçlerin yönüyle ilişkilendirdi.",
      story: "Clausius, Carnot’nun ısı makineleri üzerine kurduğu çerçeveyi daha genel bir fizik yasasına dönüştürdü. Entropi kavramı, ısının neden kendiliğinden sıcak bölgeden soğuk bölgeye aktığını ve bu sürecin neden tek yönlü olduğunu anlatmak için ortak bir dil sundu.",
      relationshipToPrevious: "Carnot’nun sorusunu genel bir yasaya dönüştürdü",
      paragraphIds: ["answer-2", "answer-4"],
      sourceIds: ["source-2"],
    },
    {
      id: "boltzmann",
      name: "Ludwig Boltzmann",
      entityType: "person",
      role: "istatistiksel temel",
      summary: "Entropiyi mikroskobik durumların olasılığıyla ilişkilendirdi.",
      story: "Boltzmann’ın yaklaşımı, termodinamikteki tek yönlülüğün atomların tek tek davranışından değil, çok sayıdaki olası düzenlenişten doğduğunu gösterdi. Böylece makroskobik yasa ile mikroskobik dünya arasında bir köprü kuruldu.",
      relationshipToPrevious: "Kavramı atomik ölçekte açıkladı",
      paragraphIds: ["answer-3", "answer-4"],
      sourceIds: ["source-3"],
    },
    {
      id: "engineers",
      name: "19. yüzyıl mühendisleri",
      entityType: "unnamed_group",
      role: "ortak pratik",
      summary: "Kuramsal soruları gerçek makineler, ölçümler ve tekrar eden uygulamalar içinde sınadı.",
      story: "Termodinamiğin geliştiği dönemde çok sayıda mühendis, teknisyen ve işçi buhar makinelerinin yapılması, işletilmesi ve ölçülmesiyle uğraşıyordu. Adlarının çoğu kuram kitaplarında yer almasa da bilimin yanıt vermeye çalıştığı pratik koşulları onlar oluşturdu.",
      relationshipToPrevious: "Kuramı gerçek dünyanın sınırlarıyla buluşturdu",
      paragraphIds: ["answer-4"],
      sourceIds: ["source-4"],
    },
  ],
  sources: [
    { id: "source-1", title: "Sadi Carnot and the steam engine", url: "https://www.britannica.com/biography/Sadi-Carnot-French-scientist" },
    { id: "source-2", title: "Rudolf Clausius and entropy", url: "https://www.britannica.com/biography/Rudolf-Clausius" },
    { id: "source-3", title: "Ludwig Boltzmann", url: "https://plato.stanford.edu/entries/statphys-Boltzmann/" },
    { id: "source-4", title: "Thermodynamics and industrial practice", url: "https://www.sciencehistory.org/education/scientific-biographies/sadi-carnot/" },
  ],
  meta: {
    model: "visual-qa-fixture",
    researchedAt: "2026-08-19T00:00:00.000Z",
    liveSearch: false,
  },
};
